#!/bin/sh

set -e -u

RESTART_SCRIPT="/home/vscode/checkpoints/hol-light-multivariate"
MESSAGE_STRING="Preloaded with multivariate real analysis."

exec restart-ocaml-checkpoint.sh "${RESTART_SCRIPT}" "${MESSAGE_STRING}"