#!/bin/sh

set -e -u

RESTART_SCRIPT="/home/vscode/checkpoints/dmtcp_restart_script.sh"
MESSAGE_STRING="Restart OCaml with HOL preloaded."

exec restart-ocaml-checkpoint.sh "${RESTART_SCRIPT}" "${MESSAGE_STRING}"
