#!/bin/sh

set -e -u

RESTART_SCRIPT="/home/vscode/checkpoints/hol-light-card"
MESSAGE_STRING="Preloaded with cardinal analysis."

exec restart-ocaml-checkpoint.sh "${RESTART_SCRIPT}" "${MESSAGE_STRING}"
