#!/bin/sh

set -e -u

RESTART_SCRIPT="/home/vscode/checkpoints/hol-light-core"
MESSAGE_STRING="Preloaded with the core library."

exec restart-ocaml-checkpoint.sh "${RESTART_SCRIPT}" "${MESSAGE_STRING}"