#!/bin/sh
cd ${HOLLIGHT_DIR}
git config --global user.email "marco.maggesi@gmail.com"
git config --global user.name  "Marco Maggesi"
git clone https://github.com/jrh13/hol-light.git
cd hol-light
git pull --rebase https://github.com/aqjune-aws/hol-light.git ckpt2
make switch-5
eval $(opam env)
make make
./make-checkpoint.sh /home/vscode/.local/bin/hol-light-core
./make-checkpoint.sh /home/vscode/.local/bin/hol-light-multivariate "loadt \"Multivariate/make.ml\""
