#!/bin/sh

HOL_LIGHT_DIR='/workspaces/hol-light-devcontainer/hol-light'
cd "${HOL_LIGHT_DIR}"
exec time ./make-checkpoint.sh ~/.local/bin/hol-light-multivariate "loadt \"/workspaces/hol-light-devcontainer/.devcontainer/more.ml\"; loadt \"Multivariate/make.ml\""